# Generated by Django 2.1.5 on 2019-02-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='', max_length=150)),
                ('subjects', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Noten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noten', models.IntegerField(default=0)),
                ('Klasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noten.Klasse')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=250)),
                ('password', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=150)),
                ('klasse', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Klasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noten.Klasse')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noten.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=250)),
                ('password', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=150)),
                ('Klasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noten.Klasse')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noten.Teacher'),
        ),
        migrations.AddField(
            model_name='noten',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noten.Student'),
        ),
        migrations.AddField(
            model_name='noten',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noten.Subject'),
        ),
    ]
