# Generated by Django 2.1.5 on 2019-03-14 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noten', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name_plural': 'Noten'},
        ),
        migrations.AlterModelOptions(
            name='prüfung',
            options={'verbose_name_plural': 'Prüfungen'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name_plural': 'Teste'},
        ),
        migrations.AlterModelOptions(
            name='unterricht',
            options={'verbose_name_plural': 'Unterrichte'},
        ),
        migrations.AddField(
            model_name='note',
            name='Subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noten.Subject'),
        ),
    ]
