# Generated by Django 2.1.7 on 2019-03-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noten', '0002_auto_20190318_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prüfung',
            options={'verbose_name_plural': 'Prüfungstyp'},
        ),
        migrations.RemoveField(
            model_name='prüfung',
            name='note',
        ),
        migrations.RemoveField(
            model_name='test',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='Unterricht',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noten.Unterricht'),
        ),
        migrations.AlterField(
            model_name='prüfung',
            name='Note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noten.Note'),
        ),
        migrations.AlterField(
            model_name='test',
            name='Note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noten.Note'),
        ),
    ]
