# Generated by Django 2.1.5 on 2019-03-07 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noten', '0002_subject_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=0)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noten.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Prüfung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=0)),
                ('Note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noten.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=0)),
                ('Note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noten.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Unterricht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='klasse',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='noten',
            name='Klasse',
        ),
        migrations.RemoveField(
            model_name='noten',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Klasse',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Student',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Klasse',
        ),
        migrations.AddField(
            model_name='unterricht',
            name='Klasse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noten.Klasse'),
        ),
        migrations.AddField(
            model_name='unterricht',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noten.Subject'),
        ),
        migrations.AddField(
            model_name='unterricht',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noten.Teacher'),
        ),
    ]
