# Generated by Django 2.1.5 on 2019-03-14 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noten', '0002_auto_20190314_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prüfungstyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='prüfung',
            name='Note',
        ),
        migrations.RemoveField(
            model_name='note',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='test',
            name='Note',
        ),
        migrations.RemoveField(
            model_name='test',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='Unterricht',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noten.Unterricht'),
        ),
        migrations.DeleteModel(
            name='Prüfung',
        ),
        migrations.AddField(
            model_name='test',
            name='Prüfungstyp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noten.Prüfungstyp'),
        ),
    ]
