# Generated by Django 2.1.5 on 2019-03-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noten', '0003_auto_20190307_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noten',
            name='Student',
        ),
        migrations.DeleteModel(
            name='Noten',
        ),
    ]
