# Generated by Django 2.1.5 on 2019-03-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noten', '0004_auto_20190314_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='Prüfungstyp',
        ),
        migrations.AddField(
            model_name='test',
            name='Note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noten.Note'),
        ),
    ]
