# Generated by Django 2.1.5 on 2019-03-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noten', '0005_auto_20190314_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prüfung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noten.Note')),
            ],
            options={
                'verbose_name_plural': 'Prüfungstyp',
            },
        ),
        migrations.RemoveField(
            model_name='test',
            name='Prüfungstyp',
        ),
        migrations.DeleteModel(
            name='Prüfungstyp',
        ),
    ]
